const fs = require('fs');
const lines = [];
function w(l) { lines.push(l); }

w('');
w('// ---------------------------------------------------------------------------');
w('// Style constants (dark theme)');
w('// ---------------------------------------------------------------------------');
w('');
w('const STYLE = {');
w('  page: { background: "#121212", color: "#E0E0E0", minHeight: "100vh", padding: "16px", fontFamily: "sans-serif" } as React.CSSProperties,');
w('  heading: { color: "#FFFFFF", marginBottom: "16px" } as React.CSSProperties,');
w('  buttonRow: { display: "flex", gap: 8, flexWrap: "wrap" as const, marginBottom: 12 } as React.CSSProperties,');
w('  primaryButton: { background: "#1565C0", color: "#FFFFFF", border: "none", borderRadius: "6px", padding: "8px 14px", fontSize: "0.9em", cursor: "pointer" } as React.CSSProperties,');
w('  dangerButton: { background: "red", color: "#FFFFFF", border: "none", borderRadius: "6px", padding: "8px 14px", fontSize: "0.9em", cursor: "pointer" } as React.CSSProperties,');
w('  testButton: { background: "#4CAF50", color: "white", border: "none", borderRadius: "6px", padding: "8px 14px", fontSize: "0.9em", cursor: "pointer" } as React.CSSProperties,');
w('  toggleLabel: { display: "flex", alignItems: "center", gap: 8, marginBottom: 12, color: "#E0E0E0" } as React.CSSProperties,');
w('  loading: { textAlign: "center" as const, padding: 32, color: "#B0B0B0" } as React.CSSProperties,');
w('  emptyState: { color: "#888" } as React.CSSProperties,');
w('  cardWrapper: { position: "relative" as const, overflow: "hidden", marginBottom: 8 } as React.CSSProperties,');
w('  timestamp: { fontSize: "0.85em", color: "#888" } as React.CSSProperties,');
w('  tagLine: { fontSize: "0.85em", color: "#B0B0B0" } as React.CSSProperties,');
w('  deleteButton: { position: "absolute" as const, right: 0, top: 0, bottom: 0, width: 80, background: "red", color: "white", border: "none", fontWeight: "bold" as const, cursor: "pointer", borderRadius: "0 8px 8px 0" } as React.CSSProperties,');
w('  modalBackdrop: { position: "fixed" as const, inset: 0, background: "rgba(0,0,0,0.7)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000 } as React.CSSProperties,');
w('  modalForm: { background: "#1E1E1E", color: "#E0E0E0", padding: 24, borderRadius: 12, minWidth: 300, display: "flex", flexDirection: "column" as const, gap: 12 } as React.CSSProperties,');
w('  modalHeading: { margin: 0, color: "#FFFFFF" } as React.CSSProperties,');
w('  modalInput: { background: "#2A2A2A", border: "1px solid #444", color: "#E0E0E0", borderRadius: "6px", padding: "8px 10px", fontSize: "1em", boxSizing: "border-box" as const, width: "100%" } as React.CSSProperties,');
w('  modalCheckboxLabel: { display: "flex", alignItems: "center", gap: 8, color: "#E0E0E0" } as React.CSSProperties,');
w('  modalButtonRow: { display: "flex", gap: 8, justifyContent: "flex-end" } as React.CSSProperties,');
w('  modalCancelButton: { background: "#333", color: "#E0E0E0", border: "none", borderRadius: "6px", padding: "8px 14px", fontSize: "0.9em", cursor: "pointer" } as React.CSSProperties,');
w('  modalSubmitButton: { background: "#1565C0", color: "#FFFFFF", border: "none", borderRadius: "6px", padding: "8px 14px", fontSize: "0.9em", cursor: "pointer" } as React.CSSProperties,');
w('  exportPanel: { background: "#1E1E1E", color: "#E0E0E0", padding: 24, borderRadius: 12, minWidth: 280, display: "flex", flexDirection: "column" as const, gap: 12 } as React.CSSProperties,');
w('  filterToggleRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 8, color: "#E0E0E0", fontSize: "0.95em" } as React.CSSProperties,');
w('  filterToggleButton: { background: "#2A2A2A", color: "#E0E0E0", border: "1px solid #444", borderRadius: "6px", padding: "4px 10px", fontSize: "0.85em", cursor: "pointer" } as React.CSSProperties,');
w('  filterSection: { background: "#1A1A1A", borderRadius: "8px", padding: "12px", marginBottom: "12px" } as React.CSSProperties,');
w('  filterChipRow: { display: "flex", flexWrap: "wrap" as const, gap: 8, marginBottom: 8 } as React.CSSProperties,');
w('  filterChip: { background: "#2A2A2A", border: "1px solid #444", borderRadius: "16px", padding: "6px 12px", color: "#E0E0E0", fontSize: "0.85em", cursor: "pointer" } as React.CSSProperties,');
w('  filterChipActive: { background: "#1565C0", border: "1px solid #1565C0", borderRadius: "16px", padding: "6px 12px", color: "#FFFFFF", fontSize: "0.85em", cursor: "pointer" } as React.CSSProperties,');
w('  filterStatusLine: { fontSize: "0.85em", color: "#888", marginBottom: 8 } as React.CSSProperties,');
w('  clearFiltersButton: { background: "#333", color: "#E0E0E0", border: "1px solid #555", borderRadius: "6px", padding: "4px 10px", fontSize: "0.85em", cursor: "pointer" } as React.CSSProperties,');
w('} as const;');
w('');
w('const BG_UNTAGGED = "#2A2A1A";');
w('const BG_TAGGED = "#1A2A1A";');
w('const COLOR_EXPENSE = "#FF6B6B";');
w('const COLOR_INCOME = "#4CAF50";');

fs.writeFileSync('_page_part2.txt', lines.join('\n'), 'utf8');
console.log('Part 2 written:', lines.length, 'lines');
